### PR TITLE
Decon then deskew

### PR DESCRIPTION
**Pull request by linshaova**
Added decon-before-deskew feature (<--dcbds>);
Support now non-rotationally averaged OTF (no flag needed, create 3D OTF in radialft using the <-3> flag).

### CODE REVIEW

**Comment by dmilkie** [comment]
Radialft does **not** create an OTF if the input tif has 51 (an odd number?) x, y pixels.
Radialft does create an OTF if the input tif has 50 (an even number?) x, y pixels.

```
I:\>radialft -3 --fixorigin 0 --background 100.1 PSF.tif OTF.tif
Created at Howard Hughes Medical Institute Janelia Research Campus. Copyright 2017. All rights reserved.
bDoCleanup=0
nx=51, ny=51, nz=51
Reading data...

In determine_center_and_background()

I:\>
```
no OTF.tif generated.  If I remove a row and a column from the PSF, then it works:

```
I:\>I:\radialft -3 --fixorigin 0 --background 100.1 "C:\Users\milkied10\Desktop\ISM data\PSFs\ePSF\LinescanConfocal_Processed_560_CamA\Linescan ConfocalConfocalPSF\Linescan ConfocalConfocal Total PSF 560_CamA_U16.tif" OTF.tif
Created at Howard Hughes Medical Institute Janelia Research Campus. Copyright 2017. All rights reserved.
bDoCleanup=0
nx=50, ny=50, nz=51
Reading data...

In determine_center_and_background()
Center of mass is (21.513, 25.364, 27.634)

Background is 100.100
Before fft
After fft

Shifting center...

I:\>
```

Might have to do with the changed code in radialft-nonSIM.cpp:
```
  int nx2 = (nx/2+1)*2;   // in case nx is odd numbered, nx2 is nx+1, not nx+2
  nxy=nx2*ny;
```

**Comment by linshaova** [comment]
I'll look into this. The cited line of code with nx2 definition was meant to deal with the odd numbered dimensions, but may be not enough.

@dmilkie , could you send me the 51x51x51 PSF that gave you the trouble? Thanks!

**Comment by dmilkie** [comment]
Here you go.

I:\>dir *.tif
 Volume in drive I is betziglab
 Volume Serial Number is 009A-9A03

 Directory of I:\

07/15/2021  08:50 AM           456,309 PSF_50.tif
07/15/2021  08:50 AM           474,489 PSF_51.tif
               2 File(s)        930,798 bytes
               0 Dir(s)  4,818,373,255,168 bytes free

*I:\>radialft.exe --input-file PSF_51.tif --output-file otf_51.tif
--nocleanup -3*
Created at Howard Hughes Medical Institute Janelia Research Campus.
Copyright 2017. All rights reserved.
bDoCleanup=0
nx=51, ny=51, nz=45
Reading data...

In determine_center_and_background()

*I:\>radialft.exe --input-file PSF_50.tif --output-file otf_50.tif
--nocleanup -3*
Created at Howard Hughes Medical Institute Janelia Research Campus.
Copyright 2017. All rights reserved.
bDoCleanup=0
nx=50, ny=50, nz=45
Reading data...

In determine_center_and_background()
Center of mass is (24.741, 24.309, 22.581)

Background is 1.114
Before fft
After fft

Shifting center...
otf3d(0) = 2.07359e+06+i0
otf3d(0) = 9.66646e+06+i-126026

I:\>dir *.tif
 Volume in drive I is betziglab
 Volume Serial Number is 009A-9A03

 Directory of I:\

07/15/2021  08:50 AM           456,309 PSF_50.tif
07/15/2021  08:50 AM           474,489 PSF_51.tif
*07/15/2021  08:52 AM           477,187 otf_50.tif*
               3 File(s)      1,407,985 bytes
               0 Dir(s)  4,818,373,255,168 bytes free

I:\>

**Comment by linshaova** [comment]
Sorry, Dan. Did you mean for me to download the files from the betziglab share? I've lost access to anything in Janelia long time ago. Could you put it on Dropbox or something? Thanks!

**Comment by linshaova** [comment]
Hi Dan, I don't know what happened, but it seems to work fine for me on both Windows and Linux. I recompiled the executables and put them in the same Dropbox folder I shared with you last week. Please try it again!

lin

**Comment by tlambert03** [comment]
hey @linshaova, where did this land.  Is this working?  do you want it in main?  Did @dmilkie try it out?

**Comment by dmilkie** [comment]
Yes.  It was working for me.

**Comment by linshaova** [comment]
I may have closed this by mistake. I thought Talley has merged this branch to master, but it actually says: Merge branch 'master' into deconThenDeskew. What does that mean?

**Comment by tlambert03** [comment]
> I thought Talley has merged this branch to master, but it actually says: Merge branch 'master' into deconThenDeskew.

It means that I merged the master branch into this branch (which is named `deconThenDeskew`).  I did it because you had a lot of conflicts with this branch and the main branch, and they were "unmergable".  I'm definitely rather apprehensive about merging this... you'll note in the diff at the top right that this PR is "huge" in the sense that it adds 2,659 lines and removes 1,916 ... 

Untitled

I assume in reality that's because you used a formatting tool or something that ended up touching a lot of lines that had nothing to do with the PR, and it's probably not that big of a PR?  In any case, it does make it risky, because if we look at the git history now it will look like every line is touched in this PR, making it hard to know what broke where, etc...

Since we don't actually have any tests running here, that's doubly "risky".

Is there any chance that you could create a new branch (branching off of the master branch here), and then manually move over just what was relevant to this PR, then create a new PR?

**Comment by linshaova** [comment]
Sorry I didn't mean to create a panic. Earlier I saw the "squash and merge" button showing green, which made me write those alarming comments. But now it's not green anymore after I reopened the PR; curious!

I understand this PR's ultimate goal is to merge my branch named `deconThenDeskew` into the master branch. But I don't understand the goal or effect of the other way around, although looking back at the commit history I saw I did something similar two years ago but forgot why I did that:

image

I think I understand your suggestions about a new PR after manual comparison. I'm just a bit confused: I thought the whole point of git is to avoid such error-prone manual revising process. What have I done wrong to end up in such a mess?

Would some tools in the `Files changed` tab (like reviewing each change) be a viable alternative way of solving the mini crisis?

**Comment by tlambert03** [comment]
merged in #23

**Pull request closed without merging**
