### PR TITLE
cmake works cross platform with conda-build, adds CI for linux

### PR DESCRIPTION
**Pull request by tlambert03**
This PR standardizes the `cmakelists.txt` file to work cross-platform provided one uses `conda build conda-recipe`.  It will install all requirements necessary for building except for the CUDA toolkit (which must be in the standard location), and on windows VisualStudio 2017/2019 must also be installed in the standard location.

I couldn't get the Windows CI build to work yet on github.  They use VisualStudio 2019, which is rather tricky to get to work with the `conda-build` pipeline, which I think requires 2017, but I could be wrong about that.  It's not strictly necessary to build with conda-build of course, but it would make distribution through conda much easier.  Currently though, one can still build for conda locally on windows with VS2017.

This does not actually deploy anything yet to conda.  Would be nice to agree on a versioning strategy before that (which can just be a manually bump)

### CODE REVIEW

**Comment by dmilkie** [comment]
Can you please update the [cmake minimum requirement](https://github.com/tlambert-forks/cudaDecon/blob/941f0ef8e3592b1029149dbaa1ec3e7b0d624042/src/CMakeLists.txt#L13) to 3.12.


`cmake_minimum_required (VERSION 2.6)`

The "add_compile_definitions" you have [here ](https://github.com/tlambert-forks/cudaDecon/blob/941f0ef8e3592b1029149dbaa1ec3e7b0d624042/src/CMakeLists.txt#L29) was added in CMAKE 3.12
https://cmake.org/cmake/help/v3.12/command/add_compile_definitions.html

**Comment by tlambert03** [comment]
definitely... thanks for catching

**Comment by tlambert03** [comment]
also, if anyone wants to see an example of the continuous integration output. you can see it here (until this merges, at which point it will happen here too):
https://github.com/tlambert-forks/cudaDecon/runs/349432924

**Comment by dmilkie** [comment]
>
> For this particular PR, I might need to write up a little bit more
> specific instructions if you want to try the conda-build pipeline (if you
> haven’t used conda build much before)
>
Yeah, using the crappy steps I put in the readme, now CMAKE is not finding
FFTW.  It looks like the CMakeLists.txt now looks it up the package that
conda installed?  I'm happy if we use conda-build instead of my 50 build
steps of README hell.  I just need you to show me how to turn the key.

[image: image.png]

**Comment by tlambert03** [comment]
yeah, probably the biggest change here is the removal of `src/cmake/FindFFTW3.cmake`... the reason I did that is because it actually fails with the fftw installed in a conda environment, and doing `conda install fftw` actually also installs a `FindFFTW3` file.  So it would be nice to figure out how to leave that file in for more conventional build pipelines. (or we all just choose to use the auto-build)

in any case, here are the steps that (I think) should allow anyone to build this PR:

1. install [miniconda](https://docs.conda.io/en/latest/miniconda.html)
2. install [cudatoolkit ](https://developer.nvidia.com/cuda-10.1-download-archive-update2)(try 10.1 for now, I haven't yet tried 10.2)
3. (windows only) install [build tools for VisualStudio](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017) 2017  (note: while VS2019 will work with the cmake file if you were to install dependencies manually  in conda and run `cmake`, it will not yet work with `conda-build`, see [here](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/building-conda-packages.html)).  For linux, the build tools will be installed by conda, so you don't need to worry about `gcc`.
4. open an `Anaconda Prompt`, and in the `base` environment, run:
```
conda config --add channels conda-forge
conda install conda-build
```

5. cd into the `cudaDecon` folder, and make sure to check out this PR.
6. (important) set the CUDA version you want to build for (this environmental variable allows you to have multiple cuda toolkits installed, and easily change which one you build against).
```
set CUDA_VERSION=10.1  # windows
export CUDA_VERSION=10.1  # linux /mac
```
7. (assuming you are still in the cudaDecon folder, in the base conda environment), build the program with: `conda build conda-recipe`

it will take a little while, and then at the end, if all goes well, it will tell you where the build artifact is (for instance, mine is at `C:\Users\tjl10\miniconda3\conda-bld\win-64\cudadeconv-1.0.3-cu10.1.tar.bz2`).  That bz2 package is intended to be uploaded to anaconda cloud.  It doesn't include all of the dependencies (those are defined in the conda recipe and will be installed automatically).  If you wanted to test it, you can install the new bundle into a test environment:
```
conda create -n test -y --use-local cudadeconv
conda activate test
cudaDeconv.exe --help
```

**Comment by tlambert03** [comment]
and if you don't want to bother with `conda-build` at all (sometimes desirable for faster iteration when testing)... then you can create a dedicated conda environment with all the necessary build dependencies.  So, instead of step 4 and on in the previous steps, do this:

```sh
conda config --add channels conda-forge
conda create -n build cmake boost-cpp libtiff fftw ninja

# then anytime you want to build it
conda activate build
mkdir build  # inside the cudaDecon folder
cd build
# activate your build tools, for instance:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
cmake ../src -G "Ninja" -DCMAKE_BUILD_TYPE=Release
ninja
```
The exe will be written to `cudaDecon\build\windows-msvc-release`.  If you change the source code, you can just rerun `ninja` and the binary will be updated.

This is the approach I generally use when working on the source code... using the `conda-build` instructions from the previous comment mostly just for deployment

**Comment by tlambert03** [comment]
got builds working on windows also with appveyor.
Last steps will be to set builds to only occur on the master branch with tagged commits (i.e. releases), and enable auto-upload to anaconda cloud.  Then no matter who updates the program cross platform binaries will be available with `conda install cudadecon`

**Comment by dmilkie** [comment]
The `conda build conda-recipe` built for me. :)  In one of the basic tests, the decon deskewed output looks the same as before (final cropping looks different, but I think that was expected). That's great!

The "ninja" build did not work for me.  See here for a hopeless looking error message.
[ninja output.txt](https://github.com/scopetools/cudaDecon/files/4031891/ninja.output.txt)
I don't particularly need this method right away, but maybe there's something easy you want to tackle.

**Comment by tlambert03** [comment]
well that's encouraging!  Thanks for trying it out

For the ninja build I think it'd be helpful to see the compiler info that usually comes at the top of the cmake command.  If you have a minute, could you try it again from a fresh command prompt and with an empty "build" directory, and paste the full thing (just so I can see each step leading up to the build)?  The ninja method relies a bit more on local environment, so I just want to see each step you're doing before running cmake.  I do think you'll want that method eventually (it's much easier to iterate when developing).

**Comment by dmilkie** [comment]
Ha.  That worked.  I'm guessing the "build" directory wasn't empty from my
previous attempts.  Thanks!

**Comment by tlambert03** [comment]
great!

**Pull request merged**
