### PR TITLE
add 3D OTF support and correct argument error

### PR DESCRIPTION
**Pull request by zichenzachwang**
1) Replicated [Linshao's original changes](https://github.com/scopetools/cudadecon/pull/23/commits/20012e5916db1b24f261420c9f7605d0ac6759a2#diff-07d7cd03faef292a49f9fae639a1a6f104405d735d3ab92a93b620ced3f259cd) but in radial_interface.cpp to allow 3D OTF generation in pycudadecon
2) Fixed the argument order issue in the function [RichardsonLucy_GPU()](https://github.com/dmilkie/cudaDecon/blob/master/src/RL-Biggs-Andrews.cpp#L692)

### CODE REVIEW

**Comment by tlambert03** [comment]
@linshaova, will want your review on this one before it merges

**Comment by tlambert03** [comment]
and @zichenzachwang, looks like it's failing to compile:

```
2024-07-15T20:44:57.6985792Z [ 75%] Building CXX object CMakeFiles/cudaDecon.dir/boostfs.cpp.o
2024-07-15T20:45:04.7288703Z [ 80%] Building CUDA object CMakeFiles/cudaDecon.dir/RLgpuImpl.cu.o
2024-07-15T20:45:21.7994762Z [ 85%] Building CUDA object CMakeFiles/cudaDecon.dir/geometryTransform.cu.o
2024-07-15T20:45:28.5055252Z [ 90%] Linking CXX executable linux-gnu-release/cudaDecon
2024-07-15T20:45:28.6762307Z /home/conda/feedstock_root/build_artifacts/cudadecon_1721075992127/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/cudaDecon.dir/linearDecon.cpp.o: in function `main':
2024-07-15T20:45:28.6763079Z linearDecon.cpp:(.text.startup.main+0x3043): undefined reference to `RichardsonLucy_GPU(cimg_library::CImg<float>&, float, GPUBuffer&, int, double, int, int, int, int, CPUBuffer&, int, int, cimg_library::CImg<float>&, cudaDeviceProp*, bool, float, bool, bool, float, bool, bool, int)'
2024-07-15T20:45:28.7022873Z collect2: error: ld returned 1 exit status
2024-07-15T20:45:28.7040804Z make[2]: *** [CMakeFiles/cudaDecon.dir/build.make:172: linux-gnu-release/cudaDecon] Error 1
2024-07-15T20:45:28.7045835Z make[1]: *** [CMakeFiles/Makefile2:158: CMakeFiles/cudaDecon.dir/all] Error 2
2024-07-15T20:45:28.7050565Z make: *** [Makefile:136: all] Error 2
```

i think you'll also need to update linearDecon.h and/or cpp

**Comment by zichenzachwang** [comment]
> and @zichenzachwang, looks like it's failing to compile:
> 
> ```
> 2024-07-15T20:44:57.6985792Z [ 75%] Building CXX object CMakeFiles/cudaDecon.dir/boostfs.cpp.o
> 2024-07-15T20:45:04.7288703Z [ 80%] Building CUDA object CMakeFiles/cudaDecon.dir/RLgpuImpl.cu.o
> 2024-07-15T20:45:21.7994762Z [ 85%] Building CUDA object CMakeFiles/cudaDecon.dir/geometryTransform.cu.o
> 2024-07-15T20:45:28.5055252Z [ 90%] Linking CXX executable linux-gnu-release/cudaDecon
> 2024-07-15T20:45:28.6762307Z /home/conda/feedstock_root/build_artifacts/cudadecon_1721075992127/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/cudaDecon.dir/linearDecon.cpp.o: in function `main':
> 2024-07-15T20:45:28.6763079Z linearDecon.cpp:(.text.startup.main+0x3043): undefined reference to `RichardsonLucy_GPU(cimg_library::CImg<float>&, float, GPUBuffer&, int, double, int, int, int, int, CPUBuffer&, int, int, cimg_library::CImg<float>&, cudaDeviceProp*, bool, float, bool, bool, float, bool, bool, int)'
> 2024-07-15T20:45:28.7022873Z collect2: error: ld returned 1 exit status
> 2024-07-15T20:45:28.7040804Z make[2]: *** [CMakeFiles/cudaDecon.dir/build.make:172: linux-gnu-release/cudaDecon] Error 1
> 2024-07-15T20:45:28.7045835Z make[1]: *** [CMakeFiles/Makefile2:158: CMakeFiles/cudaDecon.dir/all] Error 2
> 2024-07-15T20:45:28.7050565Z make: *** [Makefile:136: all] Error 2
> ```
> 
> i think you'll also need to update linearDecon.h and/or cpp

Thanks. It seems that changing just the function call is easier than changing all the functions, which is what I originally did and compiled. I have updated the changes and it seems to me it all passed?

**Review by linshaova — APPROVED** [review]

**Comment by tlambert03** [comment]
thanks @zichenzachwang!

**Pull request merged**
